apiVersion: v1
kind: Pod
metadata:
  name: nsd
  labels:
    app: nsd
spec:
  initContainers:
    - name: create-control-certs
      image: dnesting/nsd:latest
      command: ["sh", "-c", "nsd-control-setup -d /etc/nsd-control-certs && ls -l /etc/nsd-control-certs"]
      volumeMounts:
        - name: nsd-control-certs
          mountPath: /etc/nsd-control-certs
        - name: nsd-config
          mountPath: /etc/nsd
  containers:
    - name: nsd
      image: dnesting/nsd:dev
      imagePullPolicy: Always
      ports:
        - containerPort: 5333
          protocol: TCP
        - containerPort: 5333
          protocol: UDP
        - name: metrics
          containerPort: 9153
          protocol: TCP
      volumeMounts:
        - name: nsd-control-certs
          mountPath: /etc/nsd-control-certs
        - name: nsd-config
          mountPath: /etc/nsd
      livenessProbe:
        exec:
          command: ["nsd-control", "status"]
        initialDelaySeconds: 1
        periodSeconds: 5
      startupProbe:
        exec:
          command: ["nsd-control", "status"]
        periodSeconds: 1
        failureThreshold: 30
  hostNetwork: true
  volumes:
    - name: nsd-config
      configMap:
        name: nsd-config
    - name: nsd-control-certs
      emptyDir: {}
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nsd-config
data:
  example.conf: |
    remote-control:
      control-enable: yes
      control-port: 8952
      server-key-file: /etc/nsd-control-certs/nsd_server.key
      server-cert-file: /etc/nsd-control-certs/nsd_server.pem
      control-key-file: /etc/nsd-control-certs/nsd_control.key
      control-cert-file: /etc/nsd-control-certs/nsd_control.pem
    server:
      port: 5333
      metrics-enable: yes
      metrics-port: 9153
      verbosity: 1
    zone:
      name: example.com
      zonefile: example.com.zone

  example.com.zone: |
    $ORIGIN example.com. 
    $TTL 86400 
    @	IN	SOA	dns1.example.com.	hostmaster.example.com. (
    			2001010101 ; serial                     
    			21600      ; refresh after 6 hours                     
    			3600       ; retry after 1 hour                     
    			604800     ; expire after 1 week                     
    			86400 )    ; minimum TTL of 1 day  
    		     
    		           
    	IN	NS	dns1.example.com.       
    	IN	NS	dns2.example.com.        
    	
    	
    	IN	MX	10	mail.example.com.       
    	IN	MX	20	mail2.example.com.        
    
    	
    dns1	IN	A	10.0.1.1
    dns2	IN	A	10.0.1.2	
    
    			       
    server1	IN	A	10.0.1.5        
    server2	IN	A	10.0.1.6
    
           
    ftp	IN	A	10.0.1.3
    	IN	A	10.0.1.4
    	
    mail	IN	CNAME	server1
    mail2	IN	CNAME	server2
    
    
    www	IN	CNAME	server1
